### ISSUE TITLE
Request: make no CDF when no data rows ingested

### ISSUE THREAD

**Issue by aizuchi0** [das-developers/das2C#11]
Produce an INFO message and do not create an output file when the only code ingested by das3_cdf is metadata, not data. Or possibly add a flag for this?

**Comment by cpiker** [comment]
Good call.  Yep, it is certainly possible to do this.   

Getting into implementation details, since CDFs aren't streamable and since libcdf.so does not have a stdio FILE* interface (for RAM files), output is always written to a file, even when using das3_cdf as a UNIX filter in a command pipeline.  Thus, if no data records are written the permanent (or temporary) file can just be deleted.   

Sometimes for diagnostic purposes it's good to keep them around so instead of changing the default behavior I'll add an "auto-cleanup" option for empty CDFs.

**Comment by cpiker** [comment]
It's implemented (option `-c`) for cases where you're writing to  a file.  When run as a POSIX filter it still has the old behavior.
